Array manipulation 2 | Jazzmine Jimenez
Jazzmine-Jimenez/c1020-code-solutions pull request #62
Opened 2020-11-08 00:17 UTC by Jazzmine-Jimenez

2020-11-10 19:28 UTC, uzair-ashraf requested changes

2020-11-10 19:28 UTC, uzair-ashraf commented on array-manipulation-2/src/includes.js
> +    } else continue;
You don't need an else continue here, it will continue if the if statements condition isnt met anyway.

2020-11-10 19:28 UTC, uzair-ashraf commented on array-manipulation-2/src/chunk.js
> +    }
Instead of doing two if statements with a continue statement, you can just do an if elseif statement, the loop will continue regardless.

2020-11-10 19:28 UTC, uzair-ashraf commented on array-manipulation-2/src/take.js
> +    continue;
you don't need continue here, the loop will continue whether you tell it to or not.

2020-11-15 18:20 UTC, thebearingedge approved these changes

2020-11-21 23:21 UTC, merged