Object manipulation 2 | Jazzmine Jimenez
Jazzmine-Jimenez/c1020-code-solutions pull request #63
Opened 2020-11-09 02:38 UTC by Jazzmine-Jimenez

![image](https://user-images.githubusercontent.com/71475689/98494310-852bb080-21f1-11eb-82ab-3e8d1873fde6.png)

2020-11-10 23:17 UTC, uzair-ashraf requested changes

2020-11-10 23:17 UTC, uzair-ashraf commented on object-manipulation-2/src/omit.js
> +      else continue;
You don't need an else continue here, the loop will continue regardless

2020-11-10 23:17 UTC, uzair-ashraf commented on object-manipulation-2/src/pick.js
> +      }
This gets very hard to read when there is a use of a continue statements.
```
if(keys[i] === key) {
         if (source[keys[i]] !== undefined) {
          newObj[keys[i]] = source[keys[i]];
          break;
        }
}

2020-11-15 18:23 UTC, thebearingedge requested changes
Nice, just one small tweak.

2020-11-15 18:23 UTC, thebearingedge commented on object-manipulation-2/src/pick.js
> +      if (keys[i] === key) {
You can remove your `for` loop on line 4 and `if` statement on line 6.

2020-11-15 20:09 UTC, thebearingedge approved these changes

2020-11-15 20:12 UTC, merged